config/routes.rb
Rails.application.routes.draw do
  get 'posts', to: 'posts#index'
  get 'users/sign_in', to: 'posts#dashboard'
  get 'posts/dashboard', to: 'posts#dashboard'
  get 'posts/list', to: 'posts#create', as:'created_post'
  post 'posts', to: 'posts#save', as:'create_post'
  get 'posts/:id/edit', to:'posts#edit', as: 'edit_post'
  delete 'posts/:id', to: 'posts#destroy', as: 'deleted_post'
  get 'posts/:id', to: 'posts#show', as: 'show_post'
  patch 'posts/:id', to: 'posts#update', as: 'post'
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :image, presence: true
    validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: [:dashboard, :create ]
  before_action :set_post, only: [:edit, :update, :show, :destroy]
  
  def index
    @posts = Post.all.order(created_at: :desc)
    
  end

  def dashboard 
    @post = Post.new
  end

  def save
    post_data = post_params
    post_data[:content] = post_data[:content].remove("de")

    @post = Post.new(post_data)
    if @post.save
      flash[:notice] = "Post was successfully created"
      redirect_to created_post_path  
    else
      flash[:notice] = "Post was not created"
      redirect_to posts_dashboard_path(@post)     
    end    
  end

  def create
    @posts = Post.all.order(created_at: :desc)
  end

  def edit   
  end  

  def update
    post_data = post_params
    post_data[:content] = post_data[:content].remove("de")

    if @post.update(post_data)
        flash[:notice] = "Post was successfully updated"
        redirect_to created_post_path(@post)
    else
        redirect_to edit_post_path(@post)
        flash[:notice] = "Post was not updated"
    end       
  end   

  def show  
  end    

  def destroy 
    @post.destroy
    flash[:notice] = "Post was successfully deleted"
    redirect_to created_post_path
  end

  private
    def set_post
      @post = Post.find(params[:id]) 
    end
    def post_params
      params.require(:post).permit(:title, :image, :content)
    end      

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'shared/messages'%>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></  script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></  script>
  </body>
</html>

app/views/posts/create.html.erb
<h1 class="text-center">Tus artículos</h1>

<div class="container">
    <table class="table">
        <tr>
            <th>Título</th>
            <th>Fecha creación</th>
            <th>Imágen</th>
            <th>Contenido</th>
        </tr>
        <% @posts.each do |post| %>
            <tr>
                <td><%= post.title %> </td>
                <td><%= post.created_at %> </td>
                <td><%= image_tag post.image %></td>
                <td><%= post.content %></td>
                <td><%= link_to 'editar', edit_post_path(post) %></td>
                <td><%= link_to 'show', show_post_path(post) %></td>
                <td><%= link_to 'eliminar', deleted_post_path(post), method: :delete, data: {confirm: 'seguro quieres borrarlo?'} %></td>
            </tr>
        <%end%>
    </table>
    <%= link_to 'Crea un nuevo artículo', posts_dashboard_path %>
    <%= link_to 'Vista de usuarios', root_path %>
</div>

app/views/posts/dashboard.html.erb
<div>
    <h1>Bienvenido a tu espacio Blog</h1>
    <h3>Muchas gracias por tu aporte!</h3>
    <h3>Recuerda escribir posts sobre temas relevantes y no olvides guardarlo al finalizar</h3>

    <div class='row'>
        <div class="col-md-6 offset-md-3">
            <%= form_with(model: @post, local: true) do |f| %>
                <div class="form-group">
                    <%= f.label :title %> 
                    <%= f.text_field :title, class:'form-control' %>
                </div>
                <div class="form-group">
                    <%= f.label :image %> 
                    <%= f.text_field :image, class:'form-control' %>
                </div>
                <div class="form-group">
                    <%= f.label :content %> 
                    <%= f.text_field :content, class:'form-control' %>
                </div>
                <div class="offset-md-5">
                    <%= f.submit class: 'btn btn-info'%> 
            </div>    
        <% end %>
        </div>
    </div>
    <%= link_to "Ver mis posts", created_post_path, method: 'get' %>
</div>    

app/views/posts/edit.html.erb
<h1>Edita tu post</h1>

<%=render 'shared/form', post: @post %>


<%= link_to "Volver atrás", create_post_path %>

app/views/posts/index.html.erb
<nav class="navbar fixed-top navbar-dark bg-transparent">
    <span class="navbar-brand"><form method="get" action="/users/sign_in">
            <button type="submit" class="btn text-light bg-dark">
                <%= link_to "Iniciar Sesión", posts_dashboard_path %>
        </button>
    </span>  
</nav>
<br>
<div class="container, mt-3, pt-3">
    <table class="table">
        <tr>
            <th>Título</th>
            <th>Fecha creación</th>
            <th>Imágen</th>
            <th>Contenido</th>
        </tr>
        <% @posts.each do |post| %>
            <tr>
                <td><%= post.title %> </td>
                <td><%= post.created_at %> </td>
                <td><%= image_tag post.image %> </td> 
                <td><%= post.content %> </td>
            </tr>
        <%end%>
    </table>
</div>

app/views/posts/show.html.erb
<h1 class="text-center">Post</h1>
<br>
<div class="container">
    <table class="table">
        <tr>
            <th>Título</th>
            <th>Fecha creación</th>
            <th>Imágen</th>
            <th>Contenido</th>
        </tr>
        <tr>
            <td><%= @post.title %> </td>
            <td><%= @post.created_at %> </td>
            <td><%= image_tag @post.image %></td>
            <td><%= @post.content %></td>
        </tr>
    </table>    
</div>
<br>
<%= link_to "Volver atrás", created_post_path %>

app/views/shared/_form.html.erb
<div class='row'>
    <div class="col-md-6 offset-md-3">
    
        <%= form_with(model: @post, url: post_path, local: true) do |f| %>
            <div class="form-group">
                <%= f.label :title %> 
                <%= f.text_field :title, class:'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :image %> 
                <%= f.text_field :image, class:'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :content %> 
                <%= f.text_field :content, class:'form-control' %>
            </div>
            <div class="offset-md-5">
                <%= f.submit class: 'btn btn-info'%> 
                
                
            </div>    
        <% end %>
    </div>
</div>

app/views/shared/_messages.html.erb
<% flash.each do |msg| %>
    <ul class="alert alert-success" role="alert">
        <li><%= msg %></li>
    </ul>
<% end %>